"""Constants for Derivatives."""

FUTURE_PRICE_VOLUME_DATA_COLUMN = [
    "TIMESTAMP",
    "INSTRUMENT",
    "SYMBOL",
    "EXPIRY_DT",
    "STRIKE_PRICE",
    "OPTION_TYPE",
    "MARKET_TYPE",
    "OPENING_PRICE",
    "TRADE_HIGH_PRICE",
    "TRADE_LOW_PRICE",
    "CLOSING_PRICE",
    "LAST_TRADED_PRICE",
    "PREV_CLS",
    "SETTLE_PRICE",
    "TOT_TRADED_QTY",
    "TOT_TRADED_VAL",
    "OPEN_INT",
    "CHANGE_IN_OI",
    "MARKET_LOT",
    "UNDERLYING_VALUE",
]

INDICES = ["NIFTY", "FINNIFTY", "BANKNIFTY"]
